config/routes.rb
V01::Application.routes.draw do
  get "contactus/index"

  resources :words

  resources :phrases

  root :to => "phrases#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :words
end

app/models/componentisation.rb
class Componentisation < ActiveRecord::Base
  belongs_to :word
  belongs_to :phrase
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :phrases
  has_many :words
  
  def self.identify(query_string)
    # DH: Adding a ! provides a useful error message if no records are found by ActiveRecord when the DB needs seeding...
    Language.find_by_name!(query_string.to_s.camelcase)
  end
end

app/models/phrase.rb
class Phrase < ActiveRecord::Base
  has_many :translations
  has_many :phrases, :through => :translations
  
  belongs_to :language
  has_many :componentisations 
  
  def self.search(search)
    if search
      where('text LIKE ?', "%#{search}%")
    else
      scoped
    end
  end

  def self.add(str, language)
    # Initialise array to return.
    ret = Array.new
    
    # Identify the Language we are using first.
    lang = Language.identify(language)
    
    if (!str.blank?)
      # See if we can split the string.
      str.split('/').each do |phrase|
        ret << Phrase.find_or_create_by_text_and_language_id(:text => phrase, :language_id => lang.id)
        Word.add(phrase, lang.id)
      end
    end
    
    return ret
  end
end

app/models/translation.rb
class Translation < ActiveRecord::Base
  belongs_to :source_phrase, :class_name => "Phrase"
  belongs_to :target_phrase, :class_name => "Phrase"
  
  def self.add(text_from, text_to)
    puts "Translation::add(#{text_from.count}, #{text_to.count})"
    text_from.each do |source|
      text_to.each do |target|
        puts "#{source.text} -> #{target.text}"
        Translation.find_or_create_by_source_phrase_id_and_target_phrase_id(:source_phrase => source, :target_phrase => target)
      end
    end

    text_to.each do |source|
      text_from.each do |target|
        puts "#{source.text} -> #{target.text}"
        Translation.find_or_create_by_source_phrase_id_and_target_phrase_id(:source_phrase => source, :target_phrase => target)
      end
    end
  end
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :language
  belongs_to :category
  has_many :componentisations
  
  def self.search(search)
    if search
      where('text LIKE ?', "%#{search}%")
    else
      scoped
    end
  end

  def self.add(phrase, language_id)
    phrase.split(' ').each do |word|
      Word.find_or_create_by_text_and_language_id(word, language_id)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/phrases_controller.rb
class PhrasesController < ApplicationController
  # GET /phrases
  # GET /phrases.xml
  def index
    @phrases = Phrase.page(params[:page]).search(params[:search]).order(:text).per(5)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @phrases }
    end
  end

  # GET /phrases/1
  # GET /phrases/1.xml
  def show
    @phrase = Phrase.find(params[:id])
    @translations = Translation.find_all_by_source_phrase_id(@phrase)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @phrase }
    end
  end

  # GET /phrases/new
  # GET /phrases/new.xml
  def new
    @phrase = Phrase.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @phrase }
    end
  end

  # GET /phrases/1/edit
  def edit
    @phrase = Phrase.find(params[:id])
  end

  # POST /phrases
  # POST /phrases.xml
  def create
    @phrase = Phrase.new(params[:phrase])

    respond_to do |format|
      if @phrase.save
        format.html { redirect_to(@phrase, :notice => 'Phrase was successfully created.') }
        format.xml  { render :xml => @phrase, :status => :created, :location => @phrase }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @phrase.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /phrases/1
  # PUT /phrases/1.xml
  def update
    @phrase = Phrase.find(params[:id])

    respond_to do |format|
      if @phrase.update_attributes(params[:phrase])
        format.html { redirect_to(@phrase, :notice => 'Phrase was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @phrase.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /phrases/1
  # DELETE /phrases/1.xml
  def destroy
    @phrase = Phrase.find(params[:id])
    @phrase.destroy

    respond_to do |format|
      format.html { redirect_to(phrases_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  # GET /words
  # GET /words.xml
  def index
    @words = Word.page(params[:page]).search(params[:search]).order(:text)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @words }
    end
  end

  # GET /words/1
  # GET /words/1.xml
  def show
    @word = Word.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @word }
    end
  end

  # GET /words/new
  # GET /words/new.xml
  def new
    @word = Word.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @word }
    end
  end

  # GET /words/1/edit
  def edit
    @word = Word.find(params[:id])
  end

  # POST /words
  # POST /words.xml
  def create
    @word = Word.new(params[:word])

    respond_to do |format|
      if @word.save
        format.html { redirect_to(@word, :notice => 'Word was successfully created.') }
        format.xml  { render :xml => @word, :status => :created, :location => @word }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @word.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /words/1
  # PUT /words/1.xml
  def update
    @word = Word.find(params[:id])

    respond_to do |format|
      if @word.update_attributes(params[:word])
        format.html { redirect_to(@word, :notice => 'Word was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @word.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.xml
  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    respond_to do |format|
      format.html { redirect_to(words_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phrases_helper.rb
module PhrasesHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LWEasyVocab Online</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<% if notice.present? then %>
  <p class="notice"><%= notice %></p>
<% end %>
<% if alert.present? then %>
  <p class="alert"><%= alert %></p>
<% end %>
<div id="title">
</div>
<div id="menu">
  <span><%= link_to "Words", words_path %></span>
  <span><%= link_to "Phrases", phrases_path %></span>
  <span><%= link_to "Contact Us", :controller => "contactus", :method => "index" %> </span>
</div>
<br />
<%= yield %>

</body>
</html>

app/views/phrases/_form.html.erb
<%= form_for(@phrase) do |f| %>
  <% if @phrase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phrase.errors.count, "error") %> prohibited this phrase from being saved:</h2>

      <ul>
      <% @phrase.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.text_field :text %>
    <%= f.submit %>
  </div>
<% end %>

app/views/phrases/_phrases.html.erb
<table border="1">
  <tr>
    <th align="left">Phrase</th>
    <th align="center">Language</th>
    <th colspan="2">Operations</th>
  </tr>
<% @phrases.each do |phrase| %>
  <tr>  
    <td><%= link_to phrase.text, phrase %></td>
    <td align="center"><%= phrase.language.abbreviation %></td>
    <td align="center"><%= link_to 'Edit', edit_phrase_path(phrase) %></td>
    <td align="center"><%= link_to 'Destroy', phrase, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<br />
<%= paginate @phrases %>
<br />

app/views/phrases/edit.html.erb
<h1>Editing phrase</h1>

<%= render 'form' %>

<%= link_to 'Show', @phrase %> |
<%= link_to 'Back', phrases_path %>

app/views/phrases/index.html.erb
<h1>Listing Phrases</h1>

<% form_tag phrases_path, :method => 'get' do %>
<p>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil %>
</p>
<% end %>

<div id="phrases">
<%= render 'phrases' %>
</div>

<%= link_to 'New Phrase', new_phrase_path %>

app/views/phrases/index.js.erb
$("#phrases").html("<%= escape_javascript(render("phrases")) %>")

app/views/phrases/new.html.erb
<h1>New phrase</h1>

<%= render 'form' %>

<%= link_to 'Back', phrases_path %>

app/views/phrases/show.html.erb
<table>
  <tr>
    <td>
      Phrase:
    </td>
    <td>
<%= @phrase.text %>
    </td>
  </tr>
  <tr>
    <td>
      Language:
    </td>
    <td>
<%= @phrase.language.abbreviation %>
    </td>
  </tr>
  <tr>
    <td>
      Translations:
    </td>
    <td>
      <table>
        <% @translations.each do |translation| %>
        <tr>
          <td>
            <%= link_to translation.target_phrase.text, translation.target_phrase %> (<%= translation.target_phrase.language.abbreviation %>)
          </td>
        </tr>
        <% end %>
      </table>            
    </td>
  </tr>
</table>
<%= link_to 'Edit', edit_phrase_path(@phrase) %> |
<%= link_to 'Back', phrases_path %>

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.text_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :language_id %><br />
    <%= f.text_field :language_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<h1>Words</h1>

<% form_tag words_path, :method => 'get' do %>
<p>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil %>
</p>
<% end %>
<table>
  <tr>
    <th width="40%" align="left">Text</th>
    <th width="10%" align="center">Category</th>
    <th width="10%" align="center">Language</th>
    <th width="40%" colspan="2">Operations</th>
  </tr>

<% @words.each do |word| %>
  <tr>
    <td><%= link_to word.text, word %></td>
    <td align="center"><%=
if (word.category)
  word.category.name
else
  '-'
end
    %></td>
    <td align="center"><%= word.language.abbreviation %></td>
    <td align="center"><%= link_to 'Edit', edit_word_path(word) %></td>
    <td align="center"><%= link_to 'Destroy', word, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%= paginate @words %>
<br />

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @word.text %>
</p>

<p>
  <b>Category:</b>
  <%= if @word.category
        @word.category.name
  else
    'Undefined'
  end
    %>
</p>

<p>
  <b>Language:</b>
  <%= @word.language.abbreviation %>
</p>


<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>